<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: DejaVu Sans, sans-serif; color: #1a1a2e; font-size: 12px; }
    .header { background: #1e3a8a; color: #fff; padding: 32px 40px; }
    .header h1 { font-size: 34px; letter-spacing: 2px; font-weight: 700; }
    .header .num { float: right; font-size: 13px; margin-top: 14px; }
    .meta { padding: 28px 40px 8px; }
    .meta table { width: 100%; }
    .meta td { vertical-align: top; width: 50%; }
    .label { color: #1e3a8a; font-weight: 700; font-size: 13px; margin-bottom: 6px; }
    .muted { color: #555; line-height: 1.5; }
    .items { padding: 20px 40px; }
    table.lines { width: 100%; border-collapse: collapse; }
    table.lines thead th { background: #1e3a8a; color: #fff; padding: 9px 12px; text-align: left; font-size: 11px; }
    table.lines thead th.r, table.lines td.r { text-align: right; }
    table.lines tbody td { padding: 9px 12px; border-bottom: 1px solid #e5e7eb; }
    table.lines tbody tr:nth-child(even) { background: #f8fafc; }
    .totals { width: 40%; float: right; margin-top: 14px; }
    .totals td { padding: 6px 12px; }
    .totals .grand { background: #1e3a8a; color: #fff; font-weight: 700; font-size: 14px; }
    .foot { clear: both; padding: 40px; color: #888; font-size: 10px; text-align: center; }
</style>
</head>
<body>
    <div class="header">
        <span class="num">NO: {{ $invoice->invoice_number }}</span>
        <h1>INVOICE</h1>
    </div>

    <div class="meta">
        <table>
            <tr>
                <td>
                    <div class="label">Bill To:</div>
                    <div class="muted">
                        {{ $customer->first_name }} {{ $customer->last_name }}<br>
                        @if($customer->company_name){{ $customer->company_name }}<br>@endif
                        {{ $customer->shipping_address1 }}<br>
                        {{ $customer->shipping_city }}, {{ $customer->shipping_state }} {{ $customer->shipping_zip }}<br>
                        {{ $customer->email }}
                    </div>
                </td>
                <td>
                    <div class="label">From:</div>
                    <div class="muted">
                        {{ $order->shipment->ship_from_name ?? 'Warehouse Fulfillment' }}<br>
                        {{ $order->shipment->ship_from_address ?? '21043 Warrender Terrace Ln' }}<br>
                        {{ $order->shipment->ship_from_city ?? 'Richmond' }},
                        {{ $order->shipment->ship_from_state ?? 'TX' }}
                        {{ $order->shipment->ship_from_zip ?? '77407' }}
                    </div>
                    <div class="muted" style="margin-top:12px">
                        <strong>Order:</strong> {{ $order->so_number }}<br>
                        <strong>Date:</strong> {{ $invoice->issued_date->format('d M Y') }}
                    </div>
                </td>
            </tr>
        </table>
    </div>

    <div class="items">
        <table class="lines">
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Condition</th>
                    <th class="r">Qty</th>
                    <th class="r">Price</th>
                    <th class="r">Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach($order->items as $item)
                <tr>
                    <td>{{ $item->product_name }}</td>
                    <td>{{ ucfirst($item->condition) }}</td>
                    <td class="r">{{ $item->quantity }}</td>
                    <td class="r">${{ number_format($item->unit_cost_cents, 2) }}</td>
                    <td class="r">${{ number_format($item->line_total_cents, 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <table class="totals">
            <tr><td>Subtotal</td><td class="r">${{ number_format($invoice->subtotal_cents, 2) }}</td></tr>
            <tr><td>Shipping</td><td class="r">${{ number_format($invoice->shipping_cents, 2) }}</td></tr>
            <tr><td>Tax</td><td class="r">${{ number_format($invoice->tax_cents, 2) }}</td></tr>
            <tr class="grand"><td>Total</td><td class="r">${{ number_format($invoice->total_cents, 2) }}</td></tr>
        </table>
    </div>

    <div class="foot">
        Thank you for your business. &nbsp;|&nbsp; Generated by WMS on {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
